config/routes.rb
Rails.application.routes.draw do
  

  get 'photos/index'

  get 'moments' => 'events#index'
  get 'moments/:id' => 'events#show'
  post 'moments/with/:child_id/:event_id' => 'events#create_member'
  patch 'moments/:id' => 'events#update'
  put 'moments/:id' => 'events#update'
  delete 'moments/without/:child_id/:event_id' => 'events#destroy_member'

  get 'children/born' => 'children#new'

  get 'family' => 'main#index'
  get 'family/tree' => 'main#tree'
  get 'signup' => 'users#new'

  post 'sessions/create'
  
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :children
  resources :events
  resources :photos
  root 'welcome#index' # (or root :to => 'welcome#index' in Rails < 4)
  get 'home', :to => "welcome#index" # (/home redirects to index page)

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :children, through: :members
  has_many :members
  has_many :photos

  validates :start_date, :title, :location, :user_id, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user
  def index
    # @user = User.find_by_id(session[:user_id])
    @child = Child.find_by_id(params[:id])
    @events = Event.order(:start_date).all
    @event = Event.new
  end
  def show
    # @user = User.find_by_id(session[:user_id])
    @event = Event.find_by_id(params[:id])
    @children_in = Event.find(@event.id).children.where(user_id:session[:user_id])
    @children_out = @user.children.where.not(id:@children_in)
    @photos = Photo.where(event_id:@event.id)
    @photo = Photo.new
  end
  def create
    @event = Event.new(event_params)
    @event.user_id = session[:user_id]
    if @event.save
      flash[:alert] = "A moment has been added successfully."
      redirect_to '/moments'
    else
      flash[:errors] = @event.errors.full_messages.first
      redirect_to '/moments'
    end
  end

def update
    @event = Event.find_by_id(params[:id])
    if @event.update(event_params)
      flash[:alert] = "Successfully updated!"
      redirect_to "/moments/#{@event.id}"
    else
      flash[:errors] = @event.errors.full_messages.first
      redirect_to "/moment/#{@event.id}"
    end
  end

  def create_member

      # @user = User.find_by_id(session[:user_id])

      # @event = Event.find_by_id(params[:id])
      member = Member.new(child_id:params[:child_id], event_id:params[:event_id])
      if member.save
        flash[:alert] = "A child has been added successfully."
      else
        flash[:errors] = member.errors.full_messages.first
      end
      redirect_to '/moments/'+params[:event_id]
  end
  def destroy_member
    member = Member.where(child_id:params[:child_id], event_id:params[:event_id])
    member.last.destroy
    redirect_to '/moments/'+params[:event_id]
  end
  private
  def event_params
      params.require(:event).permit(:start_date, :end_date, :location, :title, :description)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="jumbotron text-center">


<div class="container">
<h1><%= @user.last_name %>'s Moments</h1>


<div class="row">
        <div class="col-sm-12 col-md-offset-4">
<%= form_for @event, :url => events_path, :html => {id: '@user.id', :multipart => true} do |f| %>
<table>
    <thead>
        <tr>
        <td></td>
        </tr>
    </thead>
    <tbody class="zebra">
        <tr>
            <td><%= f.label :start_date %></td>
            <td><%= f.date_field :start_date, class: "form-control" %></td>
        </tr>
        <tr>
            <td><%= f.label :end_date %></td>
            <td><%= f.date_field :end_date, class: "form-control" %></td>
        </tr>
        <tr>
            <td><%= f.label :location %></td>
            <td><%= f.text_field :location, class: "form-control" %></td>
        </tr>

        <tr>
            <td><%= f.label :title %></td>
            <td><%= f.text_field :title, class: "form-control" %></td>
        </tr>
        <tr>
            <td><%= f.submit :Create, class: "btn btn-primary btn-large btn-block" %></td>
        </tr>
        
    </tbody>  
</table>

<% end %>
            <% if flash[:alert].present? %>
                <h3 style="color:#337ab7"><%= flash[:alert] %></h3>
            <% end %>
            <% if flash[:errors].present? %>
                <h3 style="color:#337ab7"><%= flash[:errors] %></h3>
            <% end %>


<div class="row">
<div class="col-md-12">

    <!-- http://thecodeplayer.com/walkthrough/css3-family-tree -->
    <!--
    We will create a family tree using just CSS(3)
    The markup will be simple nested lists
    -->
    <div class="tree">
        <ul>
            <li>
                <a href=""><%= @user.last_name %> Family Events</a>
                <ul>
                <% for event in @events %>
                
                
                    <li>
                        <a href="/moments/<%= event.id %>">
                        <%= event.start_date %><br>
                        <%= event.title %>
                        </a>
                    </li>
                    
                
                <%end%>
                </ul>
            </li>
        </ul>
    </div>
    </div>


     
</div>



<style type="text/css">
/*Now the CSS*/
* {margin: 0; padding: 0;}

.tree ul {
    padding-top: 20px; position: relative;
    
    transition: all 0.5s;
    -webkit-transition: all 0.5s;
    -moz-transition: all 0.5s;
}

.tree li {
    float: left; text-align: center;
    list-style-type: none;
    position: relative;
    padding: 20px 5px 0 5px;
    
    transition: all 0.5s;
    -webkit-transition: all 0.5s;
    -moz-transition: all 0.5s;
}

/*We will use ::before and ::after to draw the connectors*/

.tree li::before, .tree li::after{
    content: '';
    position: absolute; top: 0; right: 50%;
    border-top: 1px solid #ccc;
    width: 50%; height: 20px;
}
.tree li::after{
    right: auto; left: 50%;
    border-left: 1px solid #ccc;
}

/*We need to remove left-right connectors from elements without 
any siblings*/
.tree li:only-child::after, .tree li:only-child::before {
    display: none;
}

/*Remove space from the top of single children*/
.tree li:only-child{ padding-top: 0;}

/*Remove left connector from first child and 
right connector from last child*/
.tree li:first-child::before, .tree li:last-child::after{
    border: 0 none;
}
/*Adding back the vertical connector to the last nodes*/
.tree li:last-child::before{
    border-right: 1px solid #ccc;
    border-radius: 0 5px 0 0;
    -webkit-border-radius: 0 5px 0 0;
    -moz-border-radius: 0 5px 0 0;
}
.tree li:first-child::after{
    border-radius: 5px 0 0 0;
    -webkit-border-radius: 5px 0 0 0;
    -moz-border-radius: 5px 0 0 0;
}

/*Time to add downward connectors from parents*/
.tree ul ul::before{
    content: '';
    position: absolute; top: 0; left: 50%;
    border-left: 1px solid #ccc;
    width: 0; height: 20px;
}

.tree li a{
    border: 1px solid #ccc;
    padding: 5px 10px;
    text-decoration: none;
    color: #666;
    font-family: arial, verdana, tahoma;
    font-size: 11px;
    display: inline-block;
    
    border-radius: 5px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    
    transition: all 0.5s;
    -webkit-transition: all 0.5s;
    -moz-transition: all 0.5s;
}

/*Time for some hover effects*/
/*We will apply the hover effect the the lineage of the element also*/
.tree li a:hover, .tree li a:hover+ul li a {
    background: #c8e4f8; color: #000; border: 1px solid #94a0b4;
}
/*Connector styles on hover*/
.tree li a:hover+ul li::after, 
.tree li a:hover+ul li::before, 
.tree li a:hover+ul::before, 
.tree li a:hover+ul ul::before{
    border-color:  #94a0b4;
}

/*Thats all. I hope you enjoyed it.
Thanks :)*/
</style>

app/views/events/show.html.erb
<div class="jumbotron text-center">
<h1>Moment</h1>


<%= form_for @event, :url => event_path, :html => {id: '@event.id', :multipart => true} do |f| %>
<h3>When (Start, End): <%= f.date_field :start_date, class: "form-control" %> <%= f.date_field :end_date, class: "form-control" %></h3>
<h4>Where: <%= f.text_field :location, class: "form-control", cols: "5" %></h4>
<h3>Event Name: <%= f.text_field :title, class: "form-control", rows: "5" %></h3>


        <tr>
            <td><%= f.label :description %></td>
            <td><%= f.text_area :description, class: "form-control", rows: "5" %></td>
        </tr>
        <tr>
            <td><%= f.submit :Update, class: "btn btn-primary btn-large btn-block" %></td>
        </tr>
<% end %>

<h2>Children in this event: 
<% @children_in.each do |c| %>
<button type="button" class="btn btn-default btn-md">
<%= link_to c.first_name, "/moments/without/#{c.id}/#{@event.id}", method: :delete %>
            
        <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
</button>
                        <% end %>
</h2>

                        

<h2>Children not in this event: 
<% @children_out.each do |c| %>



<button type="button" class="btn btn-default btn-md">
    <%= link_to c.first_name, "/moments/with/#{c.id}/#{@event.id}", method: :post %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    <% end %>
</button>
                             
                
</h2>

<button type="button" class="btn btn-default btn-lg">
    <a href="/moments">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Back
    </a>
</button>

<% if flash[:alert].present? %>
                <h3 style="color:#337ab7"><%= flash[:alert] %></h3>
            <% end %>
            <% if flash[:errors].present? %>
                <h3 style="color:#337ab7"><%= flash[:errors] %></h3>
            <% end %>

<br>
<br>




<h1>Photos!</h1>
<% @photos.each do |p| %>
<%= image_tag p.photo %>
<% end %>





<h1>Add a new photo for this event.</h1>
<%= form_for @photo, :url => photos_path, :html => {id: '@user.id', :multipart => true} do |f| %>
<%= f.hidden_field :event_id, value: @event.id %>
<table>
    <thead>
        <tr>
        <td></td>
        </tr>
    </thead>
    <tbody class="zebra">


        <tr>
            <td><%= f.label :photo %></td>
            <td><%= f.file_field :photo, class: "form-control" %></td>
        </tr>
        <tr>
            <td><%= f.label :title %></td>
            <td><%= f.text_field :title, class: "form-control" %></td>
        </tr>
        <tr>
            <td><%= f.label :description %></td>
            <td><%= f.text_area :description, class: "form-control" %></td>
        </tr>

        <tr>
            <td><%= f.submit :submit, class: "btn btn-primary btn-large btn-block" %></td>
        </tr>
        
    </tbody>  
</table>

<% end %>
</div>